extend-include = ["*.ipynb"]
line-length = 100
src = [
    "llm_guard",
    "tests",
]
exclude = ["examples/google_gemini.py"]

[lint]
ignore = [
    'RUF001' # String contains ambiguous `，`
]
ignore-init-module-imports = true
select = [
    'A',  # flake8-builtins
    'ASYNC',  # flake8-async
    'B',
    'ERA',  # eradicate
    'F',  # Pyflakes
    'FA',  # Future Annotations
    'I',  # Isort
    'NPY',  # NumPy Rules
    'PERF',  # performance
    'PYI',  # flake8-pyi
    'RUF',  # Ruff
    'UP',  # Pyupgrade macros
]

[lint.flake8-builtins]
builtins-ignorelist = ["input"]


[lint.isort]
combine-as-imports = true
known-first-party = [
    "llm_guard",
    "tests",
]
split-on-trailing-comma = false

[lint.pep8-naming]
ignore-names = []

[lint.per-file-ignores]
"__init__.py" = [
    "F401",  # Import imported into __init__ by unused; consider adding to `__all__` or using a redundant alias
    "F403",  # Unable to detect undefined names
    "F405",  # May be undefined, or defined from star imports
]

[lint.pydocstyle]
convention = "google"
